-- =========================================================
-- Wypełnienie tabeli produktów Insulinooporność (384 unikalnych wierszy)
-- =========================================================
DROP TABLE IF EXISTS insulinoopornosc_produkty CASCADE;
CREATE TABLE IF NOT EXISTS insulinoopornosc_produkty (
    id SERIAL PRIMARY KEY,
    rodzaj VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('zalecane', 'dozwolone', 'ograniczone', 'zakazane')),
    ilosc NUMERIC(10, 2) NULL,
    jednostka VARCHAR(50) NULL,
    komentarz TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_insulinoopornosc_produkty_rodzaj ON insulinoopornosc_produkty(rodzaj);
CREATE INDEX IF NOT EXISTS idx_insulinoopornosc_produkty_status ON insulinoopornosc_produkty(status);

INSERT INTO insulinoopornosc_produkty (rodzaj, status, ilosc, jednostka, komentarz) VALUES
('pieczywo pszenne zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo pszenne pełnoziarniste', 'dozwolone', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) pełnoziarniste', 'zalecane', NULL, NULL, NULL),
('pieczywo 100% żytnie na zakwasie', 'dozwolone', NULL, NULL, NULL),
('pieczywo 100% żytnie pełnoziarniste na zakwasie', 'zalecane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na drożdżach', 'dozwolone', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na zakwasie', 'dozwolone', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na zakwasie', 'dozwolone', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na drożdżach', 'dozwolone', NULL, NULL, NULL),
('pieczywo mieszane z dodatkami (orzechy, nasiona)', 'zalecane', NULL, NULL, NULL),
('domowy chleb wg przepisu', 'zalecane', NULL, NULL, NULL),
('drożdże piekarskie', 'zalecane', NULL, NULL, NULL),
('pszenica', 'ograniczone', NULL, NULL, NULL),
('orkisz', 'zalecane', NULL, NULL, NULL),
('płaskurka', 'dozwolone', NULL, NULL, NULL),
('samopsza', 'dozwolone', NULL, NULL, NULL),
('żyto', 'dozwolone', NULL, NULL, NULL),
('jęczmień', 'ograniczone', NULL, NULL, NULL),
('owies', 'dozwolone', NULL, NULL, NULL),
('owies bezglutenowy', 'zalecane', NULL, NULL, NULL),
('pszenżyto', 'dozwolone', NULL, NULL, NULL),
('kukurydza', 'dozwolone', 60.0, 'g', NULL),
('gryka', 'zalecane', NULL, NULL, NULL),
('proso', 'dozwolone', NULL, NULL, NULL),
('kasza manna', 'ograniczone', NULL, NULL, NULL),
('kasza kuskus', 'ograniczone', NULL, NULL, NULL),
('kasza bulgur', 'dozwolone', NULL, NULL, NULL),
('kasza pęczak', 'dozwolone', NULL, NULL, NULL),
('kasza perłowa', 'dozwolone', NULL, NULL, NULL),
('kasza gryczana biała', 'zalecane', NULL, NULL, NULL),
('kasza gryczana palona', 'zalecane', NULL, NULL, NULL),
('kasza jaglana', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane błyskawiczne', 'ograniczone', NULL, NULL, NULL),
('płatki owsiane górskie', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane zwykłe', 'zalecane', NULL, NULL, NULL),
('płatki owsiane bezglutenowe', 'dozwolone', NULL, NULL, NULL),
('otręby owsiane', 'zalecane', NULL, NULL, NULL),
('ryż biały', 'ograniczone', NULL, NULL, NULL),
('ryż brązowy pełnoziarnisty', 'zalecane', NULL, NULL, NULL),
('ryż basmati', 'zalecane', NULL, NULL, NULL),
('amarantus', 'dozwolone', NULL, NULL, NULL),
('komosa ryżowa (quinoa)', 'zalecane', NULL, NULL, NULL),
('makaron pełnoziarnisty z pszenicy', 'dozwolone', NULL, NULL, 'gotowany al dente'),
('makaron orkiszowy', 'dozwolone', NULL, NULL, NULL),
('makaron kukurydziany', 'ograniczone', NULL, NULL, NULL),
('makaron ryżowy', 'zakazane', NULL, NULL, NULL),
('makaron gryczany', 'zalecane', NULL, NULL, NULL),
('makaron z soczewicy', 'zalecane', NULL, NULL, NULL),
('makaron z ciecierzycy', 'zalecane', NULL, NULL, NULL),
('makaron z komosy ryżowej', 'zalecane', NULL, NULL, NULL),
('makaron z fasoli', 'zalecane', NULL, NULL, NULL),
('jaja kurze', 'zalecane', NULL, NULL, NULL),
('jaja przepiórcze', 'zalecane', NULL, NULL, NULL),
('jogurt naturalny', 'zalecane', NULL, NULL, NULL),
('jogurt naturalny bez laktozy', 'zakazane', NULL, NULL, NULL),
('jogurt owocowy', 'ograniczone', NULL, NULL, NULL),
('jogurt owocowy bez laktozy', 'zakazane', NULL, NULL, NULL),
('jogurt kokosowy wegański', 'dozwolone', NULL, NULL, NULL),
('kefir', 'zalecane', NULL, NULL, NULL),
('kefir bez laktozy', 'zakazane', NULL, NULL, NULL),
('masło', 'dozwolone', NULL, NULL, NULL),
('masło bez laktozy', 'zakazane', NULL, NULL, NULL),
('masło klarowane', 'dozwolone', NULL, NULL, NULL),
('maślanka naturalna', 'zalecane', NULL, NULL, NULL),
('mleko kozie', 'dozwolone', NULL, NULL, NULL),
('mleko krowie', 'dozwolone', NULL, NULL, NULL),
('mleko krowie bez laktozy', 'zakazane', NULL, NULL, NULL),
('mleko owcze', 'dozwolone', NULL, NULL, NULL),
('mleko skondensowane niesłodzone', 'zakazane', NULL, NULL, NULL),
('mleko skondensowane słodzone', 'zakazane', NULL, NULL, NULL),
('mleko w proszku', 'zakazane', NULL, NULL, NULL),
('mleko w proszku bez laktozy', 'zakazane', NULL, NULL, NULL),
('mleko zsiadłe', 'zalecane', NULL, NULL, NULL),
('mleko migdałowe/napój migdałowy', 'dozwolone', NULL, NULL, NULL),
('mleko ryżowe', 'zakazane', NULL, NULL, NULL),
('mleko owsiane/napój owsiany', 'zakazane', NULL, NULL, NULL),
('mleko kokosowe/napój kokosowy', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z izolatu białka sojowego', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z całych ziaren', 'dozwolone', NULL, NULL, NULL),
('mleko makadamia', 'zalecane', NULL, NULL, NULL),
('mleko z nerkowców', 'zalecane', NULL, NULL, NULL),
('oscypek/sery wędzone', 'dozwolone', NULL, NULL, NULL),
('ricotta', 'dozwolone', NULL, NULL, NULL),
('ricotta bez laktozy', 'zakazane', NULL, NULL, NULL),
('ser capri (typ włoski)', 'dozwolone', NULL, NULL, NULL),
('ser feta', 'zalecane', NULL, NULL, NULL),
('ser feta bez laktozy', 'ograniczone', NULL, NULL, NULL),
('ser mascarpone', 'dozwolone', NULL, NULL, NULL),
('ser mozzarella', 'zalecane', NULL, NULL, NULL),
('ser mozzarella bez laktozy', 'ograniczone', NULL, NULL, NULL),
('ser śmietankowy', 'dozwolone', NULL, NULL, NULL),
('ser śmietankowy bez laktozy', 'ograniczone', NULL, NULL, NULL),
('serek fromage (do smarowania)', 'ograniczone', NULL, NULL, NULL),
('serek homogenizowany naturalny', 'dozwolone', NULL, NULL, NULL),
('serek homogenizowany waniliowy, owocowy', 'zakazane', NULL, NULL, NULL),
('serek topiony', 'dozwolone', NULL, NULL, NULL),
('serek wiejski', 'zalecane', NULL, NULL, NULL),
('serek wiejski bez laktozy', 'ograniczone', NULL, NULL, NULL),
('serwatka', 'zakazane', NULL, NULL, NULL),
('sery pleśniowe', 'ograniczone', NULL, NULL, NULL),
('sery twarde z mleka krowiego', 'dozwolone', NULL, NULL, NULL),
('sery twarde z mleka koziego', 'dozwolone', NULL, NULL, NULL),
('ser parmezan', 'zalecane', NULL, NULL, NULL),
('skyr', 'zalecane', NULL, NULL, NULL),
('skyr bez laktozy', 'zakazane', NULL, NULL, NULL),
('śmietana kwaśna', 'dozwolone', NULL, NULL, NULL),
('śmietana kwaśna bez laktozy', 'zakazane', NULL, NULL, NULL),
('śmietanka słodka', 'dozwolone', NULL, NULL, NULL),
('śmietanka słodka bez laktozy', 'zakazane', NULL, NULL, NULL),
('tofu miękkie', 'dozwolone', NULL, NULL, NULL),
('tofu twarde', 'dozwolone', NULL, NULL, NULL),
('twaróg', 'zalecane', NULL, NULL, NULL),
('twaróg bez laktozy', 'ograniczone', NULL, NULL, NULL),
('baranina', 'dozwolone', NULL, NULL, NULL),
('cielęcina', 'zalecane', NULL, NULL, NULL),
('dziczyzna', 'zalecane', NULL, NULL, NULL),
('gęś', 'dozwolone', NULL, NULL, NULL),
('indyk', 'zalecane', NULL, NULL, NULL),
('jagnięcina', 'zalecane', NULL, NULL, NULL),
('kaczka', 'dozwolone', NULL, NULL, NULL),
('królik', 'zalecane', NULL, NULL, NULL),
('kurczak', 'zalecane', NULL, NULL, NULL),
('perliczka', 'zalecane', NULL, NULL, NULL),
('przepiórka', 'zalecane', NULL, NULL, NULL),
('wieprzowina', 'ograniczone', NULL, NULL, NULL),
('wołowina', 'dozwolone', NULL, NULL, 'wybieraj mięso chude'),
('kabanosy', 'dozwolone', NULL, NULL, 'drobiowe o wysokiej zawartości mięsa, niskiej tłuszczu, bez soi, najlepiej bezglutenowe'),
('kaszanka jęczmienna', 'ograniczone', NULL, NULL, NULL),
('kaszanka gryczana', 'dozwolone', NULL, NULL, NULL),
('kaszanka bezglutenowa', 'ograniczone', NULL, NULL, NULL),
('kiełbasa wieprzowa/mieszana', 'dozwolone', NULL, NULL, NULL),
('kiełbasa drobiowa', 'dozwolone', NULL, NULL, NULL),
('kiełbasa bezglutenowa', 'ograniczone', NULL, NULL, NULL),
('kindziuk', 'dozwolone', NULL, NULL, NULL),
('leberka (wątrobianka, pasztetowa)', 'ograniczone', NULL, NULL, NULL),
('pasztet', 'ograniczone', NULL, NULL, 'bez dodatków węglowodanowych'),
('polędwica sopocka', 'dozwolone', NULL, NULL, NULL),
('salceson', 'ograniczone', NULL, NULL, NULL),
('salami', 'dozwolone', NULL, NULL, NULL),
('suszone mięsa', 'dozwolone', NULL, NULL, NULL),
('szynka gotowana i parzona', 'ograniczone', NULL, NULL, NULL),
('szynka długodojrzewająca', 'dozwolone', NULL, NULL, NULL),
('wędzone mięsa', 'ograniczone', NULL, NULL, NULL),
('dorada', 'zalecane', NULL, NULL, NULL),
('dorsz', 'zalecane', NULL, NULL, NULL),
('flądra', 'zalecane', NULL, NULL, NULL),
('halibut świeży', 'zalecane', NULL, NULL, NULL),
('halibut wędzony', 'dozwolone', NULL, NULL, NULL),
('jesiotr', 'dozwolone', NULL, NULL, NULL),
('karp', 'dozwolone', NULL, NULL, NULL),
('lin', 'dozwolone', NULL, NULL, NULL),
('łosoś świeży', 'zalecane', NULL, NULL, NULL),
('łosoś wędzony', 'dozwolone', NULL, NULL, NULL),
('makrela wędzona', 'dozwolone', NULL, NULL, NULL),
('miętus', 'zalecane', NULL, NULL, NULL),
('mintaj', 'zalecane', NULL, NULL, NULL),
('miruna', 'zalecane', NULL, NULL, NULL),
('morszczuk', 'zalecane', NULL, NULL, NULL),
('okoń', 'zalecane', NULL, NULL, NULL),
('pstrąg świeży', 'zalecane', NULL, NULL, NULL),
('pstrąg wędzony', 'dozwolone', NULL, NULL, NULL),
('sandacz', 'zalecane', NULL, NULL, NULL),
('sardynki świeże', 'zalecane', NULL, NULL, NULL),
('sardynki w oliwie z oliwek', 'zalecane', NULL, NULL, NULL),
('sardynki wędzone', 'dozwolone', NULL, NULL, NULL),
('sola', 'zalecane', NULL, NULL, NULL),
('szczupak', 'zalecane', NULL, NULL, NULL),
('szprotki wędzone', 'dozwolone', NULL, NULL, NULL),
('szprotki w oleju/w sosie pomidorowym', 'zalecane', NULL, NULL, NULL),
('śledź', 'zalecane', NULL, NULL, NULL),
('śledź w occie w zalewie z cebulą', 'dozwolone', NULL, NULL, NULL),
('śledź w occie w zalewie bez cebuli', 'dozwolone', NULL, NULL, NULL),
('śledź w oleju w zalewie z cebulą', 'dozwolone', NULL, 'bez dodatku cukru', NULL),
('śledź w oleju w zalewie bez cebuli', 'dozwolone', NULL, 'bez dodatku cukru', NULL),
('tuńczyk świeży', 'dozwolone', NULL, 'Max 1 x tyg', NULL),
('tuńczyk w puszce w sosie własnym', 'dozwolone', NULL, 'Max 1 x tyg', NULL),
('tuńczyk w puszce w oleju', 'dozwolone', NULL, 'Max 1 x tyg', NULL),
('węgorz wędzony', 'dozwolone', NULL, 'Max 1 x mies', NULL),
('kalmary', 'zalecane', NULL, NULL, NULL),
('krewetki', 'zalecane', NULL, NULL, NULL),
('małże', 'dozwolone', NULL, NULL, NULL),
('ostrygi', 'zalecane', NULL, NULL, NULL),
('ośmiornice', 'zalecane', NULL, NULL, NULL),
('przegrzebki (muszle św. Jakuba)', 'zalecane', NULL, NULL, NULL),
('acerola', 'zalecane', NULL, NULL, NULL),
('agrest', 'zalecane', NULL, NULL, NULL),
('ananas', 'dozwolone', 80.0, 'g', 'nie solo, wyłącznie świeży'),
('arbuz', 'dozwolone', 130.0, 'g', 'nie solo'),
('aronia', 'zalecane', NULL, NULL, NULL),
('awokado', 'zalecane', NULL, NULL, NULL),
('banan niedojrzały', 'dozwolone', 50.0, 'g', NULL),
('banan dojrzały', 'zakazane', NULL, NULL, NULL),
('borówka amerykańska', 'zalecane', NULL, NULL, NULL),
('borówka czerwona', 'zalecane', NULL, NULL, NULL),
('brzoskwinia', 'dozwolone', 150.0, 'g', NULL),
('cytryna', 'zalecane', NULL, NULL, NULL),
('czarna porzeczka', 'dozwolone', 150.0, 'g', NULL),
('czereśnia', 'dozwolone', 200.0, 'g', 'nie solo'),
('czerwona porzeczka', 'zalecane', NULL, NULL, NULL),
('daktyle suszone', 'zakazane', NULL, NULL, NULL),
('dzika róża (owoc)', 'zalecane', NULL, NULL, NULL),
('figi', 'dozwolone', 100.0, 'g', 'wyłącznie świeże'),
('grapefruit', 'zalecane', NULL, NULL, NULL),
('granat', 'zalecane', NULL, NULL, NULL),
('gruszka', 'dozwolone', 120.0, 'g', 'twardsze, jedzone ze skórą'),
('jabłko', 'dozwolone', 150.0, 'g', 'twardsze, jedzone ze skórą'),
('jagody czarne', 'zalecane', NULL, NULL, NULL),
('jagody goji', 'dozwolone', 15.0, 'g', NULL),
('jeżyna', 'zalecane', NULL, NULL, NULL),
('kaki', 'dozwolone', 80.0, 'g', NULL),
('kiwi', 'dozwolone', 120.0, 'g', NULL),
('kokos', 'zalecane', NULL, NULL, NULL),
('liczi', 'dozwolone', 60.0, 'g', NULL),
('limonka', 'zalecane', NULL, NULL, NULL),
('malina', 'zalecane', NULL, NULL, NULL),
('mandarynka', 'dozwolone', 130.0, 'g', NULL),
('mango', 'dozwolone', 70.0, 'g', 'nie solo'),
('melon', 'dozwolone', 130.0, 'g', 'nie solo'),
('morela', 'dozwolone', 150.0, 'g', NULL),
('morwa', 'zalecane', NULL, NULL, NULL),
('nektarynka', 'dozwolone', 150.0, 'g', NULL),
('papaja', 'dozwolone', 130.0, 'g', NULL),
('pigwa', 'dozwolone', 150.0, 'g', 'bez dodatków węglowodanowych'),
('pomarańcza', 'dozwolone', 150.0, 'g', NULL),
('pomelo', 'dozwolone', 200.0, 'g', NULL),
('porzeczka', 'zalecane', NULL, NULL, NULL),
('poziomka', 'zalecane', NULL, NULL, NULL),
('rabarbar', 'zalecane', NULL, NULL, NULL),
('rodzynki', 'zakazane', NULL, NULL, NULL),
('rokitnik', 'zalecane', NULL, NULL, NULL),
('smoczy owoc (pitaja)', 'dozwolone', 100.0, 'g', NULL),
('śliwka', 'dozwolone', 130.0, 'g', NULL),
('śliwka suszona', 'zakazane', NULL, NULL, NULL),
('truskawka', 'zalecane', NULL, NULL, NULL),
('winogrona', 'dozwolone', 60.0, 'g', NULL),
('wiśnia', 'zalecane', NULL, NULL, NULL),
('żurawina świeża/mrożona', 'zalecane', NULL, NULL, NULL),
('żurawina suszona', 'zakazane', NULL, NULL, NULL),
('batat', 'dozwolone', 100.0, 'g', NULL),
('bakłażan', 'zalecane', NULL, NULL, NULL),
('boczniak', 'zalecane', NULL, NULL, NULL),
('bób', 'dozwolone', 200.0, 'g', 'waga z łupiną'),
('botwinka/boćwina', 'zalecane', NULL, NULL, NULL),
('brokuł', 'zalecane', NULL, NULL, NULL),
('brukiew', 'zalecane', NULL, NULL, NULL),
('brukselka', 'zalecane', NULL, NULL, NULL),
('burak', 'dozwolone', 80.0, 'g', 'nie solo'),
('burak marynowany (w occie)', 'dozwolone', 150.0, 'g', 'nie solo, zalewa bez cukru, słodzona erytrolem lub stewią'),
('cebula', 'dozwolone', NULL, NULL, 'surowa lub lekko duszona/pieczona'),
('chrzan', 'zalecane', NULL, NULL, NULL),
('cukinia', 'zalecane', NULL, NULL, NULL),
('cykoria', 'zalecane', NULL, NULL, NULL),
('czosnek', 'dozwolone', 120.0, 'g', NULL),
('dynia hokkaido', 'dozwolone', 140.0, 'g', NULL),
('dynia piżmowa', 'dozwolone', NULL, NULL, NULL),
('fasola (nasiona)', 'dozwolone', 45.0, 'g', NULL),
('groch łuskany żółty', 'dozwolone', 45.0, 'g', NULL),
('grzyby', 'zalecane', NULL, NULL, NULL),
('imbir', 'zalecane', NULL, NULL, NULL),
('jarmuż', 'zalecane', NULL, NULL, NULL),
('kalafior', 'zalecane', NULL, NULL, NULL),
('kalarepa', 'zalecane', NULL, NULL, NULL),
('kapusta', 'zalecane', NULL, NULL, NULL),
('kapusta kiszona', 'zalecane', NULL, NULL, NULL),
('karczoch', 'zalecane', NULL, NULL, NULL),
('kiełki brokuła', 'zalecane', NULL, NULL, NULL),
('kiełki rzodkiewki', 'zalecane', NULL, NULL, NULL),
('kiełki fasoli mung', 'zalecane', NULL, NULL, NULL),
('koper włoski', 'zalecane', NULL, NULL, NULL),
('kukurydza z puszki konserwowa', 'dozwolone', 60.0, 'g', NULL),
('kurki', 'zalecane', NULL, NULL, NULL),
('marchew surowa', 'zalecane', NULL, NULL, NULL),
('marchew gotowana', 'dozwolone', 100.0, 'g', NULL),
('ogórek', 'zalecane', NULL, NULL, NULL),
('ogórek kiszony', 'zalecane', NULL, NULL, NULL),
('ogórek konserwowy w occie', 'dozwolone', NULL, NULL, 'zalewa bez cukru, słodzona erytrolem lub stewią'),
('oliwki', 'zalecane', NULL, NULL, NULL),
('pak choi', 'zalecane', NULL, NULL, NULL),
('papryka chili', 'zalecane', NULL, NULL, NULL),
('papryka czerwona', 'zalecane', NULL, NULL, NULL),
('papryka żółta', 'zalecane', NULL, NULL, NULL),
('papryka zielona', 'zalecane', NULL, NULL, NULL),
('pasternak', 'dozwolone', 100.0, 'g', NULL),
('pieczarki', 'zalecane', NULL, NULL, NULL),
('pieczarki marynowane', 'dozwolone', NULL, NULL, 'zalewa bez cukru, słodzona erytrolem lub stewią'),
('pietruszka korzeń', 'dozwolone', 130.0, 'g', NULL),
('pietruszka natka', 'zalecane', NULL, NULL, NULL),
('pomidor', 'zalecane', NULL, NULL, NULL),
('pomidor cherry', 'zalecane', NULL, NULL, NULL),
('por', 'zalecane', NULL, NULL, NULL),
('roszponka', 'zalecane', NULL, NULL, NULL),
('rzepa', 'zalecane', NULL, NULL, NULL),
('rukola', 'zalecane', NULL, NULL, NULL),
('rzodkiew biała', 'zalecane', NULL, NULL, NULL),
('rzodkiewka', 'zalecane', NULL, NULL, NULL),
('sałata głowiasta', 'zalecane', NULL, NULL, NULL),
('sałata lodowa', 'zalecane', NULL, NULL, NULL),
('sałata rzymska', 'zalecane', NULL, NULL, NULL),
('seler', 'dozwolone', 130.0, 'g', NULL),
('seler naciowy', 'zalecane', NULL, NULL, NULL),
('soczewica', 'dozwolone', 45.0, 'g', NULL),
('soja', 'dozwolone', 50.0, 'g', NULL),
('szczaw', 'zalecane', NULL, NULL, NULL),
('szczypiorek', 'zalecane', NULL, NULL, NULL),
('szparagi', 'zalecane', NULL, NULL, NULL),
('szalotka', 'zalecane', NULL, NULL, NULL),
('szpinak dojrzały', 'zalecane', NULL, NULL, NULL),
('szpinak baby', 'zalecane', NULL, NULL, NULL),
('topinambur', 'dozwolone', 120.0, 'g', 'gotować ze skórką'),
('zielona fasolka', 'zalecane', NULL, NULL, NULL),
('zielony groszek', 'dozwolone', 80.0, 'g', NULL),
('ziemniak', 'dozwolone', 100.0, 'g', NULL),
('ciecierzyca', 'dozwolone', 45.0, 'g', NULL),
('groch', 'dozwolone', 45.0, 'g', NULL),
('fasola typu Jaś', 'dozwolone', 45.0, 'g', NULL),
('orzech ziemny', 'dozwolone', 30.0, 'g', NULL),
('masło orzechowe z orzechów ziemnych', 'dozwolone', 25.0, 'g', 'bez dodatków węglowodanowych, oleju palmowego'),
('nasiona pestki słonecznika', 'zalecane', NULL, NULL, NULL),
('migdały', 'zalecane', NULL, NULL, NULL),
('pestki dyni', 'zalecane', NULL, NULL, NULL),
('ziarno kakaowca (czekolada, kakao)', 'dozwolone', 25.0, 'g', 'czekolada gorzka min. 70% kakao'),
('orzech włoski', 'zalecane', NULL, NULL, NULL),
('orzech laskowy', 'zalecane', NULL, NULL, NULL),
('orzech kokosowy (wiórki)', 'zalecane', NULL, NULL, NULL),
('orzech nerkowca', 'dozwolone', 30.0, 'g', NULL),
('orzech brazylijski', 'zalecane', NULL, NULL, NULL),
('orzech pistacjowy', 'zalecane', NULL, NULL, NULL),
('orzech makadamia', 'zalecane', NULL, NULL, NULL),
('orzech pecan', 'zalecane', NULL, NULL, NULL),
('kawa', 'zalecane', NULL, NULL, NULL),
('herbata czarna', 'zalecane', NULL, NULL, NULL),
('herbata zielona', 'zalecane', NULL, NULL, NULL),
('herbata biała', 'zalecane', NULL, NULL, NULL),
('herbaty owocowe', 'dozwolone', NULL, NULL, 'bez dodatku cukru, owoców kandyzowanych, sztucznych aromatów i barwników'),
('herbata Pu erth', 'zalecane', NULL, NULL, NULL),
('yerba mate', 'zalecane', NULL, NULL, NULL),
('rooibos', 'zalecane', NULL, NULL, NULL),
('kombucha', 'zakazane', NULL, NULL, NULL),
('pokrzywa zwyczajna', 'zalecane', NULL, NULL, NULL),
('rumianek', 'zalecane', NULL, NULL, NULL),
('melisa lekarska', 'zalecane', NULL, NULL, NULL),
('mięta pieprzowa', 'zalecane', NULL, NULL, NULL),
('czystek', 'zalecane', NULL, NULL, NULL),
('sok grapefruitowy', 'zakazane', NULL, NULL, NULL),
('sok pomarańczowy', 'zakazane', NULL, NULL, NULL),
('sok jabłkowy', 'zakazane', NULL, NULL, NULL),
('sok pomidorowy', 'dozwolone', NULL, NULL, NULL),
('napoje energetyczne (energetyki)', 'zakazane', NULL, NULL, NULL),
('napoje czekoladowe', 'zakazane', NULL, NULL, NULL),
('napoje kakaowe', 'dozwolone', NULL, NULL, 'bez dodatków węglowodanowych, oleju palmowego, słodzone erytrolem lub stewią'),
('gorąca czekolada', 'dozwolone', NULL, NULL, 'bez dodatków węglowodanowych, oleju palmowego, słodzone erytrolem lub stewią'),
('pieprz czarny', 'zalecane', NULL, NULL, NULL),
('pieprz biały', 'zalecane', NULL, NULL, NULL),
('papryka słodka', 'zalecane', NULL, NULL, NULL),
('papryka ostra', 'zalecane', NULL, NULL, NULL),
('tymianek', 'zalecane', NULL, NULL, NULL),
('rozmaryn', 'zalecane', NULL, NULL, NULL),
('curry', 'dozwolone', NULL, NULL, 'bez cukru, mąki, dodatków węglowodanowych'),
('majeranek', 'zalecane', NULL, NULL, NULL),
('kminek', 'zalecane', NULL, NULL, NULL),
('liść laurowy', 'zalecane', NULL, NULL, NULL),
('ziele angielskie', 'zalecane', NULL, NULL, NULL),
('lubczyk', 'zalecane', NULL, NULL, NULL),
('czarnuszka', 'zalecane', NULL, NULL, NULL),
('sezam', 'zalecane', NULL, NULL, NULL),
('cynamon', 'zalecane', NULL, NULL, NULL),
('mak', 'zalecane', NULL, NULL, NULL),
('sos sojowy', 'dozwolone', NULL, NULL, 'bez dodatków węglowodanowych'),
('ocet', 'zalecane', NULL, NULL, NULL),
('ocet jabłkowy', 'zalecane', NULL, NULL, NULL),
('musztarda', 'dozwolone', NULL, NULL, 'bez dodatków węglowodanowych'),
('ketchup', 'dozwolone', NULL, NULL, 'wyłącznie słodzony erytrolem lub stewią'),
('olej o smaku czosnkowym', 'zalecane', NULL, NULL, NULL),
('SGF (syrop glukozowo-fruktozowy)', 'zakazane', NULL, NULL, NULL),
('glutaminian sodu MSG E621', 'dozwolone', NULL, NULL, NULL),
('sól', 'zalecane', NULL, NULL, NULL),
('sól o obniżonej zawartości sodu', 'zalecane', NULL, NULL, NULL),
('cukier', 'zakazane', NULL, NULL, NULL),
('ksylitol', 'dozwolone', NULL, NULL, NULL),
('erytrol', 'zalecane', NULL, NULL, NULL),
('stewia', 'zalecane', NULL, NULL, NULL),
('maltodekstryny', 'zakazane', NULL, NULL, NULL),
('inulina', 'zalecane', NULL, NULL, NULL);
