-- =========================================================
-- Wypełnienie tabeli produktów Niedoczynność tarczycy (384 unikalnych wierszy)
-- =========================================================
DROP TABLE IF EXISTS niedoczynnosc_tarczycy_produkty CASCADE;
CREATE TABLE IF NOT EXISTS niedoczynnosc_tarczycy_produkty (
    id SERIAL PRIMARY KEY,
    rodzaj VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('zalecane', 'dozwolone', 'ograniczone', 'zakazane')),
    ilosc NUMERIC(10, 2) NULL,
    jednostka VARCHAR(50) NULL,
    komentarz TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_niedoczynnosc_tarczycy_produkty_rodzaj ON niedoczynnosc_tarczycy_produkty(rodzaj);
CREATE INDEX IF NOT EXISTS idx_niedoczynnosc_tarczycy_produkty_status ON niedoczynnosc_tarczycy_produkty(status);

INSERT INTO niedoczynnosc_tarczycy_produkty (rodzaj, status, ilosc, jednostka, komentarz) VALUES
('pieczywo pszenne zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo pszenne pełnoziarniste Graham', 'zalecane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) zwykłe białe', 'zakazane', NULL, NULL, NULL),
('pieczywo mieszane (pszenno-żytnie) pełnoziarniste', 'zalecane', NULL, NULL, NULL),
('pieczywo 100% żytnie na zakwasie', 'dozwolone', NULL, NULL, 'najlepiej pełnoziarniste żytnie'),
('pieczywo 100% żytnie pełnoziarniste na zakwasie', 'zalecane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na drożdżach', 'zalecane', NULL, NULL, NULL),
('pieczywo 100% orkiszowe na zakwasie', 'zalecane', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na zakwasie', 'zalecane', NULL, NULL, NULL),
('pieczywo naturalnie bezglutenowe na drożdżach', 'zalecane', NULL, NULL, NULL),
('pieczywo mieszane z dodatkami (orzechy, nasiona)', 'dozwolone', NULL, NULL, 'najlepiej z mąki pełnoziarnistej'),
('domowy chleb wg przepisu', 'zalecane', NULL, NULL, NULL),
('drożdże piekarskie', 'zalecane', NULL, NULL, NULL),
('pszenica', 'dozwolone', NULL, NULL, NULL),
('orkisz', 'zalecane', NULL, NULL, NULL),
('płaskurka', 'zalecane', NULL, NULL, NULL),
('samopsza', 'zalecane', NULL, NULL, NULL),
('żyto', 'zalecane', NULL, NULL, NULL),
('jęczmień', 'zalecane', NULL, NULL, NULL),
('owies', 'zalecane', NULL, NULL, NULL),
('owies bezglutenowy', 'zalecane', NULL, NULL, NULL),
('pszenżyto', 'zalecane', NULL, NULL, NULL),
('kukurydza', 'zalecane', NULL, NULL, NULL),
('gryka', 'zalecane', NULL, NULL, NULL),
('proso', 'zalecane', NULL, NULL, NULL),
('kasza manna', 'ograniczone', NULL, NULL, NULL),
('kasza kuskus', 'ograniczone', NULL, NULL, NULL),
('kasza bulgur', 'dozwolone', NULL, NULL, NULL),
('kasza pęczak', 'dozwolone', NULL, NULL, NULL),
('kasza perłowa', 'dozwolone', NULL, NULL, NULL),
('kasza gryczana biała', 'zalecane', NULL, NULL, NULL),
('kasza gryczana palona', 'zalecane', NULL, NULL, NULL),
('kasza jaglana', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane błyskawiczne', 'ograniczone', NULL, NULL, NULL),
('płatki owsiane górskie', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane zwykłe', 'dozwolone', NULL, NULL, NULL),
('płatki owsiane bezglutenowe', 'dozwolone', NULL, NULL, NULL),
('otręby owsiane', 'dozwolone', NULL, NULL, NULL),
('ryż biały', 'dozwolone', NULL, NULL, NULL),
('ryż brązowy pełnoziarnisty', 'zalecane', NULL, NULL, NULL),
('ryż basmati', 'zalecane', NULL, NULL, NULL),
('amarantus', 'zalecane', NULL, NULL, NULL),
('komosa ryżowa (quinoa)', 'zalecane', NULL, NULL, NULL),
('makaron pełnoziarnisty z pszenicy', 'zalecane', NULL, NULL, NULL),
('makaron orkiszowy', 'zalecane', NULL, NULL, NULL),
('makaron kukurydziany', 'dozwolone', NULL, NULL, NULL),
('makaron ryżowy', 'dozwolone', NULL, NULL, NULL),
('makaron gryczany', 'zalecane', NULL, NULL, NULL),
('makaron z soczewicy', 'zalecane', NULL, NULL, NULL),
('makaron z ciecierzycy', 'zalecane', NULL, NULL, NULL),
('makaron z komosy ryżowej', 'zalecane', NULL, NULL, NULL),
('makaron z fasoli', 'zalecane', NULL, NULL, NULL),
('jaja kurze', 'zalecane', NULL, NULL, NULL),
('jaja przepiórcze', 'zalecane', NULL, NULL, NULL),
('jogurt naturalny', 'zalecane', NULL, NULL, NULL),
('jogurt naturalny bez laktozy', 'ograniczone', NULL, NULL, NULL),
('jogurt owocowy', 'zakazane', NULL, NULL, NULL),
('jogurt owocowy bez laktozy', 'zakazane', NULL, NULL, NULL),
('jogurt kokosowy wegański', 'dozwolone', NULL, NULL, NULL),
('kefir', 'zalecane', NULL, NULL, NULL),
('kefir bez laktozy', 'ograniczone', NULL, NULL, NULL),
('masło', 'dozwolone', NULL, NULL, NULL),
('masło bez laktozy', 'ograniczone', NULL, NULL, NULL),
('masło klarowane', 'dozwolone', NULL, NULL, NULL),
('maślanka naturalna', 'zalecane', NULL, NULL, NULL),
('mleko kozie', 'dozwolone', NULL, NULL, NULL),
('mleko krowie', 'dozwolone', NULL, NULL, NULL),
('mleko krowie bez laktozy', 'zakazane', NULL, NULL, NULL),
('mleko owcze', 'dozwolone', NULL, NULL, NULL),
('mleko skondensowane niesłodzone', 'ograniczone', NULL, NULL, NULL),
('mleko skondensowane słodzone', 'zakazane', NULL, NULL, NULL),
('mleko w proszku', 'ograniczone', NULL, NULL, NULL),
('mleko w proszku bez laktozy', 'zakazane', NULL, NULL, NULL),
('mleko zsiadłe', 'zalecane', NULL, NULL, NULL),
('mleko migdałowe/napój migdałowy', 'zalecane', NULL, NULL, NULL),
('mleko ryżowe', 'zakazane', NULL, NULL, NULL),
('mleko owsiane/napój owsiany', 'ograniczone', NULL, NULL, NULL),
('mleko kokosowe/napój kokosowy', 'dozwolone', NULL, NULL, NULL),
('mleko sojowe z izolatu białka sojowego', 'zakazane', NULL, NULL, NULL),
('mleko sojowe z całych ziaren', 'zakazane', NULL, NULL, NULL),
('mleko makadamia', 'zalecane', NULL, NULL, NULL),
('mleko z nerkowców', 'dozwolone', NULL, NULL, NULL),
('oscypek/sery wędzone', 'dozwolone', NULL, NULL, NULL),
('ricotta', 'zalecane', NULL, NULL, NULL),
('ricotta bez laktozy', 'ograniczone', NULL, NULL, NULL),
('ser capri (typ włoski)', 'zalecane', NULL, NULL, NULL),
('ser feta', 'dozwolone', NULL, NULL, NULL),
('ser feta bez laktozy', 'ograniczone', NULL, NULL, NULL),
('ser mascarpone', 'ograniczone', NULL, NULL, NULL),
('ser mozzarella', 'zalecane', NULL, NULL, NULL),
('ser mozzarella bez laktozy', 'ograniczone', NULL, NULL, NULL),
('ser śmietankowy', 'dozwolone', NULL, NULL, NULL),
('ser śmietankowy bez laktozy', 'ograniczone', NULL, NULL, NULL),
('serek fromage (do smarowania)', 'ograniczone', NULL, NULL, NULL),
('serek homogenizowany naturalny', 'zalecane', NULL, NULL, NULL),
('serek homogenizowany waniliowy, owocowy', 'zakazane', NULL, NULL, NULL),
('serek topiony', 'zakazane', NULL, NULL, NULL),
('serek wiejski', 'zalecane', NULL, NULL, NULL),
('serek wiejski bez laktozy', 'ograniczone', NULL, NULL, NULL),
('serwatka', 'zalecane', NULL, NULL, NULL),
('sery pleśniowe', 'ograniczone', NULL, NULL, NULL),
('sery twarde z mleka krowiego', 'dozwolone', NULL, NULL, NULL),
('sery twarde z mleka koziego', 'dozwolone', NULL, NULL, NULL),
('ser parmezan', 'dozwolone', NULL, NULL, NULL),
('skyr', 'zalecane', NULL, NULL, NULL),
('skyr bez laktozy', 'ograniczone', NULL, NULL, NULL),
('śmietana kwaśna', 'ograniczone', NULL, NULL, NULL),
('śmietana kwaśna bez laktozy', 'ograniczone', NULL, NULL, NULL),
('śmietanka słodka', 'ograniczone', NULL, NULL, NULL),
('śmietanka słodka bez laktozy', 'ograniczone', NULL, NULL, NULL),
('tofu miękkie', 'dozwolone', 120.0, 'g', 'Min 4 h od przyjęcia lewotyroksyny'),
('tofu twarde', 'dozwolone', 80.0, 'g', 'Min 4 h od przyjęcia lewotyroksyny'),
('twaróg', 'zalecane', NULL, NULL, NULL),
('twaróg bez laktozy', 'dozwolone', NULL, NULL, NULL),
('baranina', 'dozwolone', NULL, NULL, NULL),
('cielęcina', 'zalecane', NULL, NULL, NULL),
('dziczyzna', 'zalecane', NULL, NULL, NULL),
('gęś', 'dozwolone', NULL, NULL, NULL),
('indyk', 'zalecane', NULL, NULL, NULL),
('jagnięcina', 'zalecane', NULL, NULL, NULL),
('kaczka', 'dozwolone', NULL, NULL, NULL),
('królik', 'zalecane', NULL, NULL, NULL),
('kurczak', 'zalecane', NULL, NULL, NULL),
('perliczka', 'zalecane', NULL, NULL, NULL),
('przepiórka', 'zalecane', NULL, NULL, NULL),
('wieprzowina', 'dozwolone', NULL, NULL, NULL),
('wołowina', 'zalecane', NULL, NULL, NULL),
('kabanosy', 'dozwolone', NULL, NULL, 'drobiowe o wysokiej zawartości mięsa, niskiej tłuszczu, bez soi, najlepiej bezglutenowe'),
('kaszanka jęczmienna', 'ograniczone', NULL, NULL, NULL),
('kaszanka gryczana', 'ograniczone', NULL, NULL, NULL),
('kaszanka bezglutenowa', 'dozwolone', NULL, NULL, NULL),
('kiełbasa wieprzowa/mieszana', 'ograniczone', NULL, NULL, NULL),
('kiełbasa drobiowa', 'dozwolone', NULL, NULL, 'drobiowa o wysokiej zawartości mięsa, niskiej tłuszczu, bez soi, najlepiej bezglutenowa'),
('kiełbasa bezglutenowa', 'dozwolone', NULL, NULL, NULL),
('kindziuk', 'dozwolone', NULL, NULL, NULL),
('leberka (wątrobianka, pasztetowa)', 'ograniczone', NULL, NULL, NULL),
('pasztet', 'ograniczone', NULL, NULL, NULL),
('polędwica sopocka', 'dozwolone', NULL, NULL, NULL),
('salceson', 'ograniczone', NULL, NULL, NULL),
('salami', 'ograniczone', NULL, NULL, NULL),
('suszone mięsa', 'dozwolone', NULL, NULL, NULL),
('szynka gotowana i parzona', 'dozwolone', NULL, NULL, 'drobiowa o wysokiej zawartości mięsa, niskiej tłuszczu, bez soi, najlepiej bezglutenowa'),
('szynka długodojrzewająca', 'dozwolone', NULL, NULL, NULL),
('wędzone mięsa', 'ograniczone', NULL, NULL, NULL),
('dorada', 'zalecane', NULL, NULL, NULL),
('dorsz', 'zalecane', NULL, NULL, NULL),
('flądra', 'zalecane', NULL, NULL, NULL),
('halibut świeży', 'zalecane', NULL, NULL, NULL),
('halibut wędzony', 'dozwolone', 100.0, 'g', 'max 1 x tyg.'),
('jesiotr', 'dozwolone', NULL, NULL, NULL),
('karp', 'dozwolone', NULL, NULL, NULL),
('lin', 'dozwolone', NULL, NULL, NULL),
('łosoś świeży', 'dozwolone', NULL, NULL, NULL),
('łosoś wędzony', 'dozwolone', NULL, NULL, NULL),
('makrela wędzona', 'dozwolone', 100.0, 'g', 'max 1 x tyg.'),
('miętus', 'zalecane', NULL, NULL, NULL),
('mintaj', 'zalecane', NULL, NULL, NULL),
('miruna', 'zalecane', NULL, NULL, NULL),
('morszczuk', 'zalecane', NULL, NULL, NULL),
('okoń', 'dozwolone', NULL, NULL, NULL),
('pstrąg świeży', 'dozwolone', NULL, NULL, NULL),
('pstrąg wędzony', 'dozwolone', NULL, NULL, NULL),
('sandacz', 'zalecane', NULL, NULL, NULL),
('sardynki świeże', 'zalecane', NULL, NULL, NULL),
('sardynki w oliwie z oliwek', 'zalecane', NULL, NULL, NULL),
('sardynki wędzone', 'dozwolone', 100.0, 'g', 'max 1 x tyg.'),
('sola', 'zalecane', NULL, NULL, NULL),
('szczupak', 'dozwolone', NULL, NULL, NULL),
('szprotki wędzone', 'dozwolone', 100.0, 'g', 'max 1 x tyg.'),
('szprotki w oleju/w sosie pomidorowym', 'dozwolone', NULL, NULL, 'bez cukru, w oliwie z oliwek lub oleju rzepakowym'),
('śledź', 'zalecane', NULL, NULL, NULL),
('śledź w occie w zalewie z cebulą', 'zalecane', NULL, NULL, 'bez cukru i konserwantów'),
('śledź w occie w zalewie bez cebuli', 'zalecane', NULL, NULL, 'bez cukru i konserwantów'),
('śledź w oleju w zalewie z cebulą', 'zalecane', NULL, NULL, 'bez cukru i konserwantów'),
('śledź w oleju w zalewie bez cebuli', 'zalecane', NULL, NULL, 'bez cukru i konserwantów'),
('tuńczyk świeży', 'dozwolone', NULL, NULL, 'max 1 x tyg.'),
('tuńczyk w puszce w sosie własnym', 'dozwolone', NULL, NULL, 'max 1 x tyg.'),
('tuńczyk w puszce w oleju', 'dozwolone', NULL, NULL, 'max 1 x tyg., wyłącznie w oliwie z oliwek lub oleju rzepakowym'),
('węgorz wędzony', 'dozwolone', 40.0, 'g', 'okazjonalnie, max 1 x mies.'),
('kalmary', 'zalecane', NULL, NULL, NULL),
('krewetki', 'zalecane', NULL, NULL, NULL),
('małże', 'dozwolone', NULL, NULL, NULL),
('ostrygi', 'zalecane', NULL, NULL, NULL),
('ośmiornice', 'zalecane', NULL, NULL, NULL),
('przegrzebki (muszle św. Jakuba)', 'zalecane', NULL, NULL, NULL),
('acerola', 'zalecane', NULL, NULL, NULL),
('agrest', 'zalecane', NULL, NULL, NULL),
('ananas', 'dozwolone', NULL, NULL, NULL),
('arbuz', 'dozwolone', NULL, NULL, NULL),
('aronia', 'zalecane', NULL, NULL, NULL),
('awokado', 'zalecane', NULL, NULL, NULL),
('banan niedojrzały', 'zalecane', NULL, NULL, NULL),
('banan dojrzały', 'ograniczone', NULL, NULL, NULL),
('borówka amerykańska', 'zalecane', NULL, NULL, NULL),
('borówka czerwona', 'zalecane', NULL, NULL, NULL),
('brzoskwinia', 'zalecane', NULL, NULL, NULL),
('cytryna', 'zalecane', NULL, NULL, NULL),
('czarna porzeczka', 'zalecane', NULL, NULL, NULL),
('czereśnia', 'zalecane', NULL, NULL, NULL),
('czerwona porzeczka', 'zalecane', NULL, NULL, NULL),
('daktyle suszone', 'ograniczone', NULL, NULL, NULL),
('dzika róża (owoc)', 'zalecane', NULL, NULL, NULL),
('figi', 'dozwolone', NULL, NULL, NULL),
('grapefruit', 'dozwolone', NULL, NULL, NULL),
('granat', 'zalecane', NULL, NULL, NULL),
('gruszka', 'zalecane', NULL, NULL, NULL),
('jabłko', 'dozwolone', NULL, NULL, NULL),
('jagody czarne', 'zalecane', NULL, NULL, NULL),
('jagody goji', 'zalecane', NULL, NULL, NULL),
('jeżyna', 'zalecane', NULL, NULL, NULL),
('kaki', 'zalecane', NULL, NULL, NULL),
('kiwi', 'zalecane', NULL, NULL, NULL),
('kokos', 'zalecane', NULL, NULL, NULL),
('liczi', 'zalecane', NULL, NULL, NULL),
('limonka', 'zalecane', NULL, NULL, NULL),
('malina', 'zalecane', NULL, NULL, NULL),
('mandarynka', 'dozwolone', NULL, NULL, NULL),
('mango', 'dozwolone', NULL, NULL, NULL),
('melon', 'dozwolone', NULL, NULL, NULL),
('morela', 'dozwolone', NULL, NULL, NULL),
('morwa', 'zalecane', NULL, NULL, NULL),
('nektarynka', 'dozwolone', NULL, NULL, NULL),
('papaja', 'dozwolone', NULL, NULL, NULL),
('pigwa', 'zalecane', NULL, NULL, NULL),
('pomarańcza', 'dozwolone', NULL, NULL, NULL),
('pomelo', 'dozwolone', NULL, NULL, NULL),
('porzeczka', 'zalecane', NULL, NULL, NULL),
('poziomka', 'zalecane', NULL, NULL, NULL),
('rabarbar', 'zalecane', NULL, NULL, NULL),
('rodzynki', 'ograniczone', NULL, NULL, NULL),
('rokitnik', 'zalecane', NULL, NULL, NULL),
('smoczy owoc (pitaja)', 'dozwolone', NULL, NULL, NULL),
('śliwka', 'dozwolone', NULL, NULL, NULL),
('śliwka suszona', 'dozwolone', NULL, NULL, NULL),
('truskawka', 'zalecane', NULL, NULL, NULL),
('winogrona', 'dozwolone', NULL, NULL, NULL),
('wiśnia', 'zalecane', NULL, NULL, NULL),
('żurawina świeża/mrożona', 'zalecane', NULL, NULL, NULL),
('żurawina suszona', 'dozwolone', NULL, NULL, 'bez cukru'),
('batat', 'zalecane', NULL, NULL, NULL),
('bakłażan', 'dozwolone', NULL, NULL, NULL),
('boczniak', 'zalecane', NULL, NULL, NULL),
('bób', 'dozwolone', NULL, NULL, 'Min 4 h od przyjęcia lewotyroksyny'),
('botwinka/boćwina', 'zalecane', NULL, NULL, NULL),
('brokuł', 'dozwolone', NULL, NULL, NULL),
('brukiew', 'dozwolone', NULL, NULL, NULL),
('brukselka', 'dozwolone', NULL, NULL, NULL),
('burak', 'zalecane', NULL, NULL, NULL),
('burak marynowany (w occie)', 'zalecane', NULL, NULL, NULL),
('cebula', 'zalecane', NULL, NULL, NULL),
('chrzan', 'zalecane', NULL, NULL, NULL),
('cukinia', 'zalecane', NULL, NULL, NULL),
('cykoria', 'zalecane', NULL, NULL, NULL),
('czosnek', 'zalecane', NULL, NULL, NULL),
('dynia hokkaido', 'zalecane', NULL, NULL, NULL),
('dynia piżmowa', 'dozwolone', NULL, NULL, NULL),
('fasola (nasiona)', 'zalecane', NULL, NULL, NULL),
('groch łuskany żółty', 'zalecane', NULL, NULL, NULL),
('grzyby', 'zalecane', NULL, NULL, NULL),
('imbir', 'zalecane', NULL, NULL, NULL),
('jarmuż', 'dozwolone', NULL, NULL, 'wyłącznie gotowany'),
('kalafior', 'dozwolone', NULL, NULL, 'wyłącznie gotowany'),
('kalarepa', 'dozwolone', 100.0, 'g', NULL),
('kapusta', 'dozwolone', 150.0, 'g', NULL),
('kapusta kiszona', 'dozwolone', 150.0, 'g', NULL),
('karczoch', 'zalecane', NULL, NULL, NULL),
('kiełki brokuła', 'dozwolone', NULL, NULL, NULL),
('kiełki rzodkiewki', 'zalecane', NULL, NULL, NULL),
('kiełki fasoli mung', 'zalecane', NULL, NULL, NULL),
('koper włoski', 'zalecane', NULL, NULL, NULL),
('kukurydza z puszki konserwowa', 'zalecane', NULL, NULL, NULL),
('kurki', 'zalecane', NULL, NULL, NULL),
('marchew surowa', 'zalecane', NULL, NULL, NULL),
('marchew gotowana', 'zalecane', NULL, NULL, NULL),
('ogórek', 'zalecane', NULL, NULL, NULL),
('ogórek kiszony', 'zalecane', NULL, NULL, NULL),
('ogórek konserwowy w occie', 'zalecane', NULL, NULL, NULL),
('oliwki', 'zalecane', NULL, NULL, NULL),
('pak choi', 'dozwolone', NULL, NULL, NULL),
('papryka chili', 'dozwolone', NULL, NULL, NULL),
('papryka czerwona', 'dozwolone', NULL, NULL, NULL),
('papryka żółta', 'dozwolone', NULL, NULL, NULL),
('papryka zielona', 'dozwolone', NULL, NULL, NULL),
('pasternak', 'zalecane', NULL, NULL, NULL),
('pieczarki', 'zalecane', NULL, NULL, NULL),
('pieczarki marynowane', 'zalecane', NULL, NULL, NULL),
('pietruszka korzeń', 'zalecane', NULL, NULL, NULL),
('pietruszka natka', 'zalecane', NULL, NULL, NULL),
('pomidor', 'dozwolone', NULL, NULL, NULL),
('pomidor cherry', 'dozwolone', NULL, NULL, NULL),
('por', 'zalecane', NULL, NULL, NULL),
('roszponka', 'zalecane', NULL, NULL, NULL),
('rzepa', 'zalecane', NULL, NULL, NULL),
('rukola', 'zalecane', NULL, NULL, NULL),
('rzodkiew biała', 'zalecane', NULL, NULL, NULL),
('rzodkiewka', 'zalecane', NULL, NULL, NULL),
('sałata głowiasta', 'zalecane', NULL, NULL, NULL),
('sałata lodowa', 'zalecane', NULL, NULL, NULL),
('sałata rzymska', 'zalecane', NULL, NULL, NULL),
('seler', 'zalecane', NULL, NULL, NULL),
('seler naciowy', 'zalecane', NULL, NULL, NULL),
('soczewica', 'zalecane', NULL, NULL, NULL),
('soja', 'dozwolone', NULL, NULL, 'Min 4 h od przyjęcia lewotyroksyny'),
('szczaw', 'zalecane', NULL, NULL, NULL),
('szczypiorek', 'zalecane', NULL, NULL, NULL),
('szparagi', 'zalecane', NULL, NULL, NULL),
('szalotka', 'zalecane', NULL, NULL, NULL),
('szpinak dojrzały', 'dozwolone', 30.0, 'g', NULL),
('szpinak baby', 'dozwolone', 30.0, 'g', NULL),
('topinambur', 'zalecane', NULL, NULL, NULL),
('zielona fasolka', 'zalecane', NULL, NULL, NULL),
('zielony groszek', 'zalecane', NULL, NULL, NULL),
('ziemniak', 'zalecane', NULL, NULL, NULL),
('ciecierzyca', 'zalecane', NULL, NULL, NULL),
('groch', 'dozwolone', NULL, NULL, NULL),
('fasola typu Jaś', 'dozwolone', NULL, NULL, NULL),
('orzech ziemny', 'dozwolone', NULL, NULL, NULL),
('masło orzechowe z orzechów ziemnych', 'dozwolone', NULL, NULL, NULL),
('nasiona pestki słonecznika', 'zalecane', NULL, NULL, NULL),
('migdały', 'zalecane', NULL, NULL, NULL),
('pestki dyni', 'zalecane', NULL, NULL, NULL),
('ziarno kakaowca (czekolada, kakao)', 'zalecane', NULL, NULL, NULL),
('orzech włoski', 'zalecane', NULL, NULL, NULL),
('orzech laskowy', 'zalecane', NULL, NULL, NULL),
('orzech kokosowy (wiórki)', 'zalecane', NULL, NULL, NULL),
('orzech nerkowca', 'zalecane', NULL, NULL, NULL),
('orzech brazylijski', 'zalecane', NULL, NULL, NULL),
('orzech pistacjowy', 'zalecane', NULL, NULL, NULL),
('orzech makadamia', 'zalecane', NULL, NULL, NULL),
('orzech pecan', 'zalecane', NULL, NULL, NULL),
('kawa', 'zalecane', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny i posiłku'),
('herbata czarna', 'dozwolone', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny i posiłku'),
('herbata zielona', 'dozwolone', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny i posiłku'),
('herbata biała', 'dozwolone', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny i posiłku'),
('herbaty owocowe', 'dozwolone', NULL, NULL, 'bez dodatku cukru, owoców kandyzowanych, sztucznych aromatów i barwników'),
('herbata czerwona Pu erth', 'zalecane', NULL, NULL, NULL),
('yerba mate', 'dozwolone', NULL, NULL, 'Min 1 h od przyjęcia lewotyroksyny i posiłku'),
('rooibos', 'zalecane', NULL, NULL, NULL),
('kombucha', 'zakazane', NULL, NULL, NULL),
('pokrzywa zwyczajna', 'zalecane', NULL, NULL, NULL),
('rumianek', 'zalecane', NULL, NULL, NULL),
('melisa lekarska', 'zalecane', NULL, NULL, NULL),
('mięta pieprzowa', 'zalecane', NULL, NULL, NULL),
('czystek', 'zalecane', NULL, NULL, NULL),
('sok grapefruitowy', 'ograniczone', NULL, NULL, NULL),
('sok pomarańczowy', 'ograniczone', NULL, NULL, NULL),
('sok jabłkowy', 'ograniczone', NULL, NULL, NULL),
('sok pomidorowy', 'dozwolone', NULL, NULL, NULL),
('napoje energetyczne (energetyki)', 'zakazane', NULL, NULL, NULL),
('napoje czekoladowe', 'zakazane', NULL, NULL, NULL),
('napoje kakaowe', 'zakazane', NULL, NULL, NULL),
('gorąca czekolada', 'zakazane', NULL, NULL, NULL),
('pieprz czarny', 'zalecane', NULL, NULL, NULL),
('pieprz biały', 'zalecane', NULL, NULL, NULL),
('papryka słodka', 'zalecane', NULL, NULL, NULL),
('papryka ostra', 'zalecane', NULL, NULL, NULL),
('tymianek', 'zalecane', NULL, NULL, NULL),
('rozmaryn', 'zalecane', NULL, NULL, NULL),
('curry', 'zalecane', NULL, NULL, NULL),
('majeranek', 'zalecane', NULL, NULL, NULL),
('kminek', 'zalecane', NULL, NULL, NULL),
('liść laurowy', 'zalecane', NULL, NULL, NULL),
('ziele angielskie', 'zalecane', NULL, NULL, NULL),
('lubczyk', 'zalecane', NULL, NULL, NULL),
('czarnuszka', 'zalecane', NULL, NULL, NULL),
('sezam', 'zalecane', NULL, NULL, NULL),
('cynamon', 'zalecane', NULL, NULL, NULL),
('mak', 'zalecane', NULL, NULL, NULL),
('sos sojowy', 'dozwolone', NULL, NULL, NULL),
('ocet', 'dozwolone', NULL, NULL, NULL),
('ocet jabłkowy', 'zalecane', NULL, NULL, NULL),
('musztarda', 'dozwolone', NULL, NULL, NULL),
('ketchup', 'dozwolone', NULL, NULL, NULL),
('olej o smaku czosnkowym', 'zalecane', NULL, NULL, NULL),
('SGF (syrop glukozowo-fruktozowy)', 'zakazane', NULL, NULL, NULL),
('glutaminian sodu MSG E621', 'dozwolone', NULL, NULL, NULL),
('sól', 'dozwolone', NULL, NULL, NULL),
('sól o obniżonej zawartości sodu', 'dozwolone', NULL, NULL, NULL),
('cukier', 'dozwolone', NULL, NULL, NULL),
('ksylitol', 'zalecane', NULL, NULL, NULL),
('erytrol', 'zalecane', NULL, NULL, NULL),
('stewia', 'zalecane', NULL, NULL, NULL),
('maltodekstryny', 'zakazane', NULL, NULL, NULL),
('inulina', 'zalecane', NULL, NULL, NULL);
